name: Execute SSH Commands

on: [push, pull_request, workflow_dispatch]

jobs:
  my-job: 
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Run SSH Commands
        id: ssh
        uses: my-job: ./.github/workflows/action.yml
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          commands: |
            ls -a
            pm2 list
            pm2 restart 0